---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-api/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: np-scheduler-api
  labels:
    helm.sh/chart: np-scheduler-api-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-api
    app.kubernetes.io/instance: abc
  
data:
  CID: "vn"
  JWT_EXPIRATION: "28800"
  JWT_SECRET: "36c8dda71cc687a94c2bec6a51969c59"
  LOG_LEVEL: "DEBUG"
  MONGODB_URI: "mongodb://dev:nextlend-dev@10.1.150.40:27017/nextlend-scheduler"
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "dev"
  ZID: "vn01"
  ELASTIC_APM_ENABLE_LOG_CORRELATION: "true"
  ELASTIC_APM_ENVIRONMENT: "np-scheduler-dev"
  ELASTIC_APM_SERVER_URL: "http://10.1.150.114:8200"
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-logtime/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: np-scheduler-logtime
  labels:
    helm.sh/chart: np-scheduler-logtime-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-logtime
    app.kubernetes.io/instance: abc
  
data:
  ELASTIC_APM_ENABLE_LOG_CORRELATION: "true"
  ELASTIC_APM_ENVIRONMENT: "np-scheduler-dev"
  ELASTIC_APM_SERVER_URL: "http://10.1.150.114:8200"
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-web/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: np-scheduler-web
  labels:
    helm.sh/chart: np-scheduler-web-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-web
    app.kubernetes.io/instance: abc
  
data:
  VUE_APP_API_URL: "np-scheduler-api:8080/bgs"
  ELASTIC_APM_ENABLE_LOG_CORRELATION: "true"
  ELASTIC_APM_ENVIRONMENT: "np-scheduler-dev"
  ELASTIC_APM_SERVER_URL: "http://10.1.150.114:8200"
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-api/templates/service.yaml
apiVersion: v1
kind: Service
  
metadata:
  name: np-scheduler-api
  labels:
    helm.sh/chart: np-scheduler-api-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-api
    app.kubernetes.io/instance: abc
  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: np-scheduler-api
    app.kubernetes.io/instance: abc
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-logtime/templates/service.yaml
apiVersion: v1
kind: Service
  
metadata:
  name: np-scheduler-logtime
  labels:
    helm.sh/chart: np-scheduler-logtime-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-logtime
    app.kubernetes.io/instance: abc
  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: np-scheduler-logtime
    app.kubernetes.io/instance: abc
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-web/templates/service.yaml
apiVersion: v1
kind: Service
  
metadata:
  name: np-scheduler-web
  labels:
    helm.sh/chart: np-scheduler-web-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-web
    app.kubernetes.io/instance: abc
  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app.kubernetes.io/name: np-scheduler-web
    app.kubernetes.io/instance: abc
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scheduler-api
  labels:
    helm.sh/chart: np-scheduler-api-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-api
    app.kubernetes.io/instance: abc
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: np-scheduler-api
      app.kubernetes.io/instance: abc
  template:
    metadata:
      annotations:
        checksum/config: f524f8944da7741b5f7a6abf57d88eaca42997bde6284df4d8f39eda52c1f865
      labels:
        app.kubernetes.io/name: np-scheduler-api
        app.kubernetes.io/instance: abc
    spec:
      imagePullSecrets:
        - name: nextpay-harbor
      restartPolicy: Always
      containers:
        - name: np-scheduler-api
          image: "hub.saobang.vn/nextpay/nextpay-servcie-np-scheduler-api:dev-cf1f89ad"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: np-scheduler-api
          volumeMounts:
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi
      volumes:
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-logtime/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scheduler-logtime
  labels:
    helm.sh/chart: np-scheduler-logtime-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-logtime
    app.kubernetes.io/instance: abc
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: np-scheduler-logtime
      app.kubernetes.io/instance: abc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: np-scheduler-logtime
        app.kubernetes.io/instance: abc
    spec:
      imagePullSecrets:
        - name: nextpay-harbor
      restartPolicy: Always
      containers:
        - name: np-scheduler-logtime
          image: "hub.saobang.vn/nextpay/np-schedule/np-scheduler-logtime:dev-68ffec6f"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: np-scheduler-logtime
          volumeMounts:
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-scheduler-web
  labels:
    helm.sh/chart: np-scheduler-web-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-web
    app.kubernetes.io/instance: abc
  
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: np-scheduler-web
      app.kubernetes.io/instance: abc
  template:
    metadata:
      annotations:
        checksum/config: 5edd2b8281d631e2978c8d503c74dc255736227dda80242ddee7ac39565246fd
      labels:
        app.kubernetes.io/name: np-scheduler-web
        app.kubernetes.io/instance: abc
    spec:
      imagePullSecrets:
        - name: nextpay-harbor
      restartPolicy: Always
      containers:
        - name: np-scheduler-web
          image: "hub.saobang.vn/nextpay/nextpay-servcie-np-scheduler-web:dev-68ffec6e"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: np-scheduler-web
          volumeMounts:
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-api/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: np-scheduler-api
  labels:
    helm.sh/chart: np-scheduler-api-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-api
    app.kubernetes.io/instance: abc
  
spec:
  rules:
    - host: "dev-scheduler-api.nextpay.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: np-scheduler-api
                port:
                  number: 8080
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-logtime/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: np-scheduler-logtime
  labels:
    helm.sh/chart: np-scheduler-logtime-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-logtime
    app.kubernetes.io/instance: abc
  
spec:
  rules:
    - host: "dev-logtime.nextpay.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: np-scheduler-logtime
                port:
                  number: 80
---
# Source: np-scheduler/charts/np-scheduler/charts/services/charts/np-scheduler-web/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: np-scheduler-web
  labels:
    helm.sh/chart: np-scheduler-web-0.1.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: np-scheduler-web
    app.kubernetes.io/instance: abc
  
spec:
  rules:
    - host: "dev-scheduler.nextpay.vn"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: np-scheduler-web
                port:
                  number: 80
